apiv1/users/urls.py
from django.urls import path, include
from .views import login_api

urlpatterns = [
    path('login/', login_api),
]

bsb/urls.py
from django.urls import path
from .views import (
    all_bsb,
    bsb_view,
    bsb_assignments,
    bsb_assignment,
    add_bsb_assignment, edit_bsb_assignment, edit_bsb, add_bsb, results, add_answer_ball,
    bsb_problems, bsb_problem, edit_bsb_problem, get_attempt, add_bsb_problem, bsb_quizess, post_bsb_question,
    add_bsb_quiz, quiz_answer,
    clone_bsb,delete_bsb
)
urlpatterns = [
    path('', all_bsb, name='all_bsb'),
    path('control/<int:id>/', bsb_view, name='bsb'),
    path('control/<int:id>/assignments/', bsb_assignments, name='bsb_assignments'),
    path('control/<int:id>/assignments/assignment/<int:id1>/', bsb_assignment, name='bsb_assignment'),
    path('control/<int:id>/assignments/add/', add_bsb_assignment, name='add_bsb_assignment'),
    path('control/<int:id>/assignments/assignment/<int:id1>/edit/', edit_bsb_assignment, name='edit_bsb_assignment'),
    path('control/<int:id>/edit/', edit_bsb, name='bsb_edit'),
    path('control/<int:id>/clone/', clone_bsb, name='clone_bsb'),
    path('control/<int:id>/delete/', delete_bsb, name='delete_bsb'),
    path('create/', add_bsb, name='add_bsb'),
    path('control/<int:id>/results/', results, name='bsb_results'),
    path('control/<int:id>/student/answer/<int:id1>/', add_answer_ball, name='bsb_student_answer'),
    path('control/<int:id>/problems/', bsb_problems, name='bsb_problems'),
    path('control/<int:id>/problems/problem/<int:id1>/', bsb_problem, name='bsb_problem'),
    path('control/<int:id>/problems/problem/<int:id1>/edit/', edit_bsb_problem, name='edit_bsb_problem'),
    path('control/<int:id>/attempts/attempt/<int:id1>/', get_attempt, name='bsb_attempt'),
    path('control/<int:id>/problems/add/', add_bsb_problem, name="add_bsb_problem"),
    path('control/<int:id>/tests/', bsb_quizess, name="bsb_tests"),
    path('control/<int:id>/tests/post/', post_bsb_question, name='bsb_quiz_post'),
    path('control/<int:id>/tests/add/', add_bsb_quiz, name='add_bsb_quiz'),
    path('control/<int:id>/tests/answer/<int:id1>/', quiz_answer, name='bsb_quiz_answer')
]

tests_teachers/urls.py
from django.contrib import admin
from django.http import JsonResponse
from django.urls import path, include
from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static

from bsb.models import BSB
from posts.models import Post
from users.models import MyUser
from assignments.models import Assignment, StudentAnswer
from django.conf.urls.static import static
from searchs.views import permission_denied, server_error, bad_request
from quizess.models import Quiz
from Masalalar.models import Masala
from assignments.models import Assignment
from courses.models import Course


def home(request):
    return render(request, 'home.html')

def notFound(request, exception):
    unread_assign = None
    unread_answerca2 = []
    if request.user.is_authenticated:
        unread_assign = Assignment.objects.filter(is_readed=False, student=request.user)

        unread_answerca = StudentAnswer.objects.filter(is_readed=False)
        unread_answerca2 = []
        for unread_answerca1 in unread_answerca:

            if unread_answerca1.assignment.author == request.user:
                a = unread_answerca1
                unread_answerca2.append(a)
    return render(request, '404.html', {'unread_assign': unread_assign, 'unread_answerca': len(unread_answerca2)})

def get_counts_api(reqeust):
    data={}
    a = MyUser.objects.filter(is_teacher=True).count()
    data['t']=a
    b = MyUser.objects.filter(is_teacher=False).count()
    data['s']=b
    c=Quiz.objects.all().count()
    data['q']=c
    d = Masala.objects.all().count()
    data['m']=d
    f = BSB.objects.count()
    data['c']=f
    j = Assignment.objects.count()
    data['a'] = j
    data['c1'] = Course.objects.count()
    return JsonResponse(data)

def get_api_2(reqeust):
    courses = Course.objects.all().order_by('users')[:8]
    data = {}
    for i in courses:
        data1 = {
            'title': i.title,
            'id': i.id,
            'about': i.summary,
            'users': i.users.count(),
            'teg': i.tags.all()[0].title if i.tags else ''
        }
        data[i.id] = data1
    return JsonResponse(data)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('tests/', include('quizess.views.urls.add')),
    path('tests/', include('quizess.views.urls.detail')),
    path('tests/', include('quizess.views.urls.edit')),
    path('', include('searchs.urls')),
    path('404/', notFound, name='notFound'),
    path('informatics/', include('infotmatika.urls')),
    path('assignments/', include('assignments.urls')),
    path('chats/', include('my_messages.urls')),
    path('classes/', include('sinflar.urls')),
    path('controls/', include('bsb.urls')),
    path('users/', include('baholar.urls')),
    path('courses/', include('courses.urls')),
    path('courses/', include('courses.creates_url')),
    path('courses/', include('courses.edits_url')),
    path('olympiad-solutions/', include('olimpiads.urls')),
    path('api1/', get_counts_api),
    path('api2/', get_api_2),
    path('api/v1/', include('apiv1.routes'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = notFound
handler403 = permission_denied
handler400 = bad_request
handler500 = server_error

users/urls.py
from django.urls import path
from .views import own_assignment, all_teachers, all_students, profile_view, theme_changer, signup, login_view, \
    update_profile, \
    own_problems, own_tests, own_posts, own_controls, add_friends, all_freiends, check_user_status, \
    check_users_status, get_top_users, add_admin_view, liked_posts, solved_problems, profile_attempts_view, \
    courses_view,tests_view, onlines, update_user_with_admin_view
from searchs.views import last_searchs, all_searchs_delete

urlpatterns = [
    path('teachers/', all_teachers, name='all_teachers'),
    path('students/', all_students, name='all_students'),
    path('profile/<str:username>/', profile_view, name='profile'),
    path('theme/', theme_changer, name='theme_changer'),
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('update/', update_profile, name='update_profile'),
    path('profile/<str:username>/assignments/', own_assignment, name='own_assignment'),
    path('profile/<str:username>/controls/', own_controls, name='own_controls'),
    path('profile/<str:username>/add_friend/', add_friends, name='add_friends'),
    path('profile/<str:username>/friends/', all_freiends, name='all_freiends'),
    path('profile/<str:username>/check_user_status/', check_user_status, name='check_user_status'),
    path('profile/<str:username>/solved-problems/', solved_problems, name='solved_problems'),
    path('profile/<str:username>/attempts/', profile_attempts_view, name='profile_attempts_view'),
    path('profile/<str:username>/courses/', courses_view, name='courses_view'),
    path('profile/<str:username>/questions/', tests_view, name='tests_view'),
    path('users_status/<int:id>/', check_users_status, name='check_users_status'),
    path('get_top_users/', get_top_users, name='get_top_users'),
    path('add-super-user', add_admin_view),
    path('onlines/', onlines),
    path('profile/<str:username>/edit-admin/', update_user_with_admin_view, name='update_user_with_admin_view'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from apiv1.naturaltime import naturaltime
from django.utils import timezone
from datetime import timedelta
from django.core import validators
from django.utils.deconstruct import deconstructible
import re

@deconstructible
class ASCIIUsernameValidator(validators.RegexValidator):
    regex = r"^[\w_]+\Z"
    flags = re.ASCII


class MyUser(AbstractUser):
    username_validator = ASCIIUsernameValidator()
    fanlar = (
        ('Matematika', 'Matematika'),
        ('ona_tili', 'Ona Tili'),
        ('musiqa', 'Musiqa'),
        ('rus_tili', 'Rus tili'),
        ('english', 'Chet tili'),
        ('jismoniy_tarbiya', 'Jismoniy tarbiya'),
        ('tarix', 'Tarix'),
        ('geografiya', 'Geografiya'),
        ('tasviriy_sanat', 'Tasviriy san\'at'),
        ('informatika', 'Informatika'),
        ('direktor', 'Direktor'),
        ('urin_bosar', 'Direktor o\'rin bosari'),
        ('psixolog', 'Psixolog'),
        ('maslahatchi', 'Maslahatchi'),
        ('chqbt', 'Chqbt'),
        ('kutubxonaxhi', 'Kutubxona'),
        ('biologiya', 'Biologiya'),
        ('kimyo', 'Kimyo'),
        ('huquq', 'Huquq'),
        ('fizika', 'Fizika'),
        ('texnologiya', 'Texnologiya'),
        ('iqtisod', 'Iqtisod')
    )
    is_teacher = models.BooleanField(default=False)
    fan = models.CharField(max_length=30, choices=fanlar, blank=True, null=True)

    sinflar = (
        ('5.1', '5.1'),
        ('5.2', '5.2'),
        ('6.1', '6.1'),
        ('6.2', '6.2'),
        ('7.1', '7.1'),
        ('7.2', '7.2'),
        ('7.3', '7.3'),
        ('8.1', '8.1'),
        ('8.2', '8.2'),
        ('8.3', '8.3'),
        ('9.1', '9.1'),
        ('9.2', '9.2'),
        ('9.3', '9.3'),
        ('10.1', '10.1'),
        ('10.2', '10.2'),
        ('10.3', '10.3'),
        ('11.1', '11.1'),
        ('11.2', '11.2'),
        ('11.3', '11.3'),
        ('Guest', 'Guest'),
    )
    is_student = models.BooleanField(default=True)
    sinf = models.CharField(max_length=30, choices=sinflar, blank=True, null=True)
    themes = (
        ('default', 'dark'),
        ('light', 'light'),
        ('green', 'green'),
        ('black', 'black'),
        ('brown', 'brown'),
    )
    navbar_colors = (
        ('light', 'light'),
        ('blue', 'blue'),
        ('green', 'green'),
        ('brown', 'brown'),
        ('black', 'black'),
    )

    last_visit = models.DateTimeField(null=True, blank=True)

    font = models.CharField(max_length=30, default='sans-serif')
    navbar_color = models.CharField(max_length=30, choices=navbar_colors, default='blue')
    ball = models.FloatField(default=0.0)
    theme = models.CharField(max_length=30, choices=themes, default='light')
    bio = models.TextField(default='.')
    friends = models.ManyToManyField('self',related_name='user_friends', blank=True, null=True)

    is_create_course = models.BooleanField(default=False)
    is_create_test = models.BooleanField(default=False)
    is_create_ass = models.BooleanField(default=False)
    is_create_masala = models.BooleanField(default=False)
    is_create_yechim = models.BooleanField(default=False)
    is_create_bsb = models.BooleanField(default=False)

    def status(self):
        now = timezone.now()
        
        now_10 = now - timedelta(minutes = 1)
        if now_10 < self.last_visit < now:
            return 'Online'
        return naturaltime(self.last_visit)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import MyUser
# from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    sinflar = (
        ('5.1', '5.1'),
        ('5.2', '5.2'),
        ('6.1', '6.1'),
        ('6.2', '6.2'),
        ('7.1', '7.1'),
        ('7.2', '7.2'),
        ('7.3', '7.3'),
        ('8.1', '8.1'),
        ('8.2', '8.2'),
        ('8.3', '8.3'),
        ('9.1', '9.1'),
        ('9.2', '9.2'),
        ('9.3', '9.3'),
        ('10.1', '10.1'),
        ('10.2', '10.2'),
        ('10.3', '10.3'),
        ('11.1', '11.1'),
        ('11.2', '11.2'),
        ('11.3', '11.3'),
        ('Guest', 'Guest'),
    )
    username = forms.CharField(label='Foydalanuvchi nomi', widget=forms.TextInput(attrs={'class': 'form-control bg-dark text-white'}), help_text='Siz bu yerga faqat alfabitning [A-z] bo\'lgan harflar yoki sonlarni kiritishingiz mumkin!', error_messages={'unique': 'Bu foydalanuvchi nomi allaqachon tizimda'})
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control bg-dark text-white'}), label='Email manzil', help_text='O\'zingizning email manzilingizni kiriting')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control bg-dark text-white'}), required=False, label='Ism', help_text='O\'zingizning ismingizni yozing')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control bg-dark text-white'}), required=False,
                    label='Familya', help_text='O\'zingizning familyangizni yozing')
    sinf = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control bg-dark text-white'}, choices=sinflar,), label='Sinf', help_text='O\'z sinfingizni tanlang', choices=sinflar)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control bg-dark text-white'}), help_text='Esingizda qoladigan parolni yozing!', label='Parol')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control bg-dark text-white'}), help_text='Parolni takrorlang', label='Parolni takrorlang')


    class Meta:
        fields = ['username', 'email', 'first_name', 'last_name', 'sinf',]
        model = MyUser

class UserProfile(forms.ModelForm):

    username = forms.CharField(label='Foydalanuvchi nomi',
                               widget=forms.TextInput(attrs={'class': 'form-control bg-dark text-white'}),
                               help_text='Siz bu yerga faqat alfabitning [A-z] bo\'lgan harflar yoki sonlarni kiritishingiz mumkin!',
                               error_messages={'unique': 'Bu foydalanuvchi nomi allaqachon tizimda'})
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control bg-dark text-white'}),
                             label='Email manzil', help_text='O\'zingizning email manzilingizni kiriting')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control bg-dark text-white'}),
                                 required=False, label='Ism', help_text='O\'zingizning ismingizni yozing')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control bg-dark text-white'}),
                                required=False,
                                label='Familya', help_text='O\'zingizning familyangizni yozing')
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control bg-dark text-white'}),
                          help_text='O\'zingiz haqingizda ma\'lumot beirng', label='Haqida')

    class Meta:
        fields = ['username', 'email', 'first_name', 'last_name', 'bio', ]
        model = MyUser

apiv1/users/views.py
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpRequest
import json
from users.models import MyUser

@csrf_exempt
def login_api(request: HttpRequest):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data['username']
        password = data['password']
        try:
            user = MyUser.objects.get(username=username)
        except:
            return JsonResponse({'status': 'User not found'})
        
        if user.check_password(password):
            return JsonResponse({'status': 'ok', 'api_token': user.api_token, 'username':user.username, 'full_name': user.get_full_name()})
        else:
            return JsonResponse({'status': 'Password not true'})
    else:
        return JsonResponse({'status': 'error'})
    
def notification(request, ):
    pass

templates/users/add_super_user1.html
{% extends 'base.html' %}

{% block title %}Admin yaratish{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item active bg-dark" aria-current="page">Admin yaratish</li>
{% endblock breadcrumb %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">Foydalanuvchi nomini kiriting</label>
            <input type="text" id="username" name="username" class="bg-dark form-control" placeholder="Foydalanuvchi nomi misol uchun: admin">
        </div>
        <div class="mb-3">
            <input type="checkbox"  id="is_staff" name="is_staff" class="form-check-input">
            <label for="is_staff">Foydalanuvchi Admin Ham qilib tayinlaysizmi?</label>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary"><i class="fa fa-plus"></i> Admin qilib tayinlash</button>
        </div>
    </form>
{% endblock content %}

templates/users/all.html
{% extends 'base.html' %}
{% block title %}
    O'qituvchilar
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item active text-white" aria-current="page">O'qituvchilar</li>
{% endblock breadcrumb %}

{% block content %}
    <div class="table-responsive">
        <table class="table table-bordered border-white bg-dark text-white">
            <thead>
                <tr>
                    <th scope="col">Foydalanuvchi nomi</th>
                    <th scope="col">Ismi sharif</th>
                    <th scope="col">Fan</th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                    <tr>
                        <td><a href="{% url 'profile' teacher.username %}">{{teacher.username}}</a></td>
                        <td>{{teacher.first_name}} {{teacher.last_name}}</td>
                        <td>{{teacher.fan|title}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/users/all_friends.html
{% extends 'base.html' %}

{% block title %}Do'stlar{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item"><a href="{% url 'profile' profile.username %}">{{profile.username|title}}</a></li>
<li class="breadcrumb-item active bg-dark">Do'stlar</li>
{% endblock breadcrumb %}


{% block content %}
<div class="row">
    <div class="col-md-3 text-center profile-sticky">
        <div class="card bg-dark p-3 mb-3">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Student_%28example%29.svg/444px-Student_%28example%29.svg.png?20180722153736"
                alt="IMG" width="100%" style="border-radius: 50%;background-color: transparent;">
            <div class="my-2 fs-3">
                {{profile.first_name}} {{profile.last_name}}
            </div>
            <span style="font-size: 13px;">{{profile.email}}</span>
            <span  style="font-size: 13px;" class="user-status"></span>
            <button class="user-menu-opener"><i class="fa-solid fa-user-gear"></i> Hisob menyusi <i class="fa fa-chevron-down"></i></button>
            <ul class="profile-items my-3">
                <li><a  href="/users/profile/{{profile.username}}/"><i class="fa fa-user"></i> Profil</a></li>
                {% if user == profile %}
                <li><a href="/users/update/"><i class="fa fa-pen"></i> Tahirirlash</a></li>
                <li><a href="/chats/"><i class="fa fa-comment"></i> Suhbatlar</a></li>
                {% endif %}
                {% if not profile.is_teacher and not profle.is_staff %}
                <li><a href="/users/profile/{{profile.username}}/prices/assignment/"><i class="bx bx-football"></i> Topshiriqdan  olgan ballar</a></li>
                <li><a href="/users/profile/{{profile.username}}/prices/controls/"><i class="bx bx-football"></i> Nazoratlardan olgan ballar</a></li>
                {% else %}
                <li><a href="/users/profile/{{profile.username}}/assignments/"><i class="bx bx-football"></i> Topshiriqlar</a></li>
                <li><a href="/users/profile/{{profile.username}}/controls/"><i class="bx bx-football"></i> Nazoratlar</a></li>
                {% endif %}
                <li><a href="/users/profile/{{profile.username}}/solved-problems/"><i class="fa fa-check"></i> Masalalar</a></li>
                <li><a href="/users/profile/{{profile.username}}/attempts/"><i class="fab fa-strava"></i> Urinishlar</a></li>
                <li><a href="/users/profile/{{profile.username}}/courses/"><i class="fa fa-book"></i> Kurslar</a></li>
                <li><a href="/users/profile/{{profile.username}}/questions/"><i class="fa fa-question"></i> Testlar</a></li>
                <li class="active-profile-item"><a href="#"><i class="fa fa-users"></i> Do'stlar</a></li>
                {% if user.is_staff and user != profile %}
                <li><a href="/users/profile/{{profile.username}}/edit-admin/"><i class="fa fa-pen"></i> Tahrirlash</a></li>
                {% endif %}
            </ul>
            </ul>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card bg-dark text-white m-2">
            <div class="card-header p-0">
                <form method="GET" class="input-group mb-2">
                    <input requiered value="{{search}}" type="text" aria-label="Qidiruv" name="search" class="form-control bg-dark text-white" placeholder="Qidiruv">
                    <select hidden class="form-control bg-dark text-white" id="id_sinf"><option value="all" selected>Hammasi</option>

    </select>
                    <button class="input-group-text btn btn-primary">Qidirish</button>
                </form>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-bordered border-white bg-dark text-white">
                    <thead>
                        <tr>
                            <th scope="col">Foydalanuvchi nomi</th>
                            <th scope="col">Ismi sharif</th>
                            <th scope="col">Sinf</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for teacher in object.object_list %}
                            <tr>
                                <td><a href="{% url 'profile' teacher.username %}">{{teacher.username}}</a></td>
                                <td>{{teacher.first_name}} {{teacher.last_name}}</td>
                                <td>{{teacher.sinf|title}}</td>
                            </tr>
                        {% empty %}
                        <tr class="text-center">
                            <td class="text-center" colspan="3"><h1>Hech narsa topilmadi</h1></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% if object.num_pages != 1 %}
                    <tfoot>
                        <tr>
                            <th colspan="8">

                                <div class="pages text-center">

                                    <nav aria-label="Page navigation example" class="text-center">
                                        <ul class="pagination bg-dark text-center justify-content-center my-3">
                                            {% if page_obj.has_previous %}
                                                <li class="page-item bg-dark"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Orqaga</a></li>

                                                {% if page_obj.number > 3 %}
                                                    <li class="page-item"> <a class="page-link" href="?page=1">1</a></li>
                                                        {% if page_obj.number > 4 %}
                                                            <li class="page-item"><span class="page-link">...</span></li>
                                                        {% endif %}
                                                    {% endif %}
                                                {% endif %}

                                                {% for num in page_obj.paginator.page_range %}
                                                    {% if page_obj.number == num %}
                                                        <li class="page-item"><a class="page-link active disabled bg-dark" href="?page={{ num }}">{{ num }}</a></li>
                                                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                    {% endif %}
                                                {% endfor %}

                                                {% if page_obj.has_next %}
                                                    {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %} <span class="page-link">...</span>
                                                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                                    {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %} <li class="page-item"><a class="page-link"
                                                            href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                                {% endif %}

                                                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Oldinga</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </th>
                        </tr>
                    </tfoot>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    const status = document.querySelector('.user-status');

    const now = new Date('Avg 23, 14:47:23');
    function checkOnlineStatus() {
        fetch('/users/profile/{{profile.username}}/check_user_status/')
            .then(response => response.json())
            .then(data => {
                if (data.is_online) {
                    status.innerHTML = '<p style="color: green !important;">Online</p>'
                } else {
                    status.innerHTML = `<p style="color: rgb(230,10,10) !important;">${data.time}</p>`
                }
            })
            .catch(error => console.log(error));
    }
    checkOnlineStatus();
    setInterval(checkOnlineStatus, 5000);

</script>
{% endblock %}

templates/users/all_students.html
{% extends 'base.html' %}
{% block title %}
    O'quvchilar
{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item active text-white" aria-current="page">O'quvchilar</li>
{% endblock breadcrumb %}

{% block content %}
    <div class="table-responsive">
        <table class="table table-bordered border-white bg-dark text-white">
            <thead>
                <tr>
                    <th scope="col">Foydalanuvchi nomi</th>
                    <th scope="col">Ismi sharif</th>
                    <th scope="col">Sinf</th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in students %}
                    <tr>
                        <td><a href="{% url 'profile' teacher.username %}">{{teacher.username}}</a></td>
                        <td>{{teacher.first_name}} {{teacher.last_name}}</td>
                        <td>{{teacher.sinf|title}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/users/last_search.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item"><a href="{% if profile.is_teacher %}/users/teachers/{% else %}/users/teachers/{% endif %}">{% if profile.is_teacher %}O'qituvchilar{% else %}O'quvchilar{% endif %}</a></li>
<li class="breadcrumb-item"><a href="{% url 'profile' profile.username %}">{{profile.username|title}}</a></li>
<li class="breadcrumb-item active">Qidiruv tarixi</li>
{% endblock breadcrumb %}

{% block content %}
{% include 'users/profile_header.html' %}
        <div class="card bg-dark text-white">
            <div class="card-title">
                <a href="{% url 'all_search_delete' user.username %}" class="btn btn-outline-danger m-3">Hammasini o'chirish</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered text-white">
                        <tbody>
                            {% for search in latest_search %}
                                <tr>
                                    <th>{{search.body}}</th>
                                    <td>{{search.date_searched|date:'d.m.Y | h:i'}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
{% endblock content %}

templates/users/onlines.html
{% extends "base.html" %}

{% load replace_text_n %}

{% block title %}Online Foydalanuvchilar{% endblock title %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
<li class="breadcrumb-item active bg-dark" aria-current="page">Online Foydalanuvchilar</li>
{% endblock breadcrumb %}

{% block content %}
<div class="card bg-dark p-1">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Foydalanuvchi</th>
                    <th>Sinf</th>
                </tr>
            </thead>
            <tbody>
                {% for user1 in users %}
                {% if user1.status == 'Online' %}
                <tr>
                    <td><a href="/users/profile/{{user1.username}}/">{{user1.get_full_name}}</a></td>
                    <td>{% if user1|get_class %}<a href="/classes/class/{{user1|get_class}}/">{{user1.sinf}}</a>{% else %}Admin{% endif %}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}